### ISSUE TITLE
Avoid Gray Highlighting 

### ISSUE THREAD

**Issue by GirayK3** [kelciour/edit_field_during_review#15]
Every time I delete a paragraph, the text moved to the top is highlighted in gray. How can I prevent this? 

Thanks in regards 

(you can see what i mean in the linked pic)
<img width="832" alt="Bildschirmfoto 2024-06-02 um 14 45 08" src="https://github.com/kelciour/edit-field-during-review/assets/171490254/5895943d-9aa7-4f26-8a70-94d46bb52754">

**Comment by kelciour** [comment]
The add-on is pretty much archived by now. Please try Edit Field During Review (Cloze) instead.

https://ankiweb.net/shared/info/385888438
