### ISSUE TITLE
the edit-field-during-review add-on

### ISSUE THREAD

**Issue by Seven430** [kelciour/edit_field_during_review#16]
Thank you for your edit-field-during-review add-on. I'm not sure if it's appropriate to bother you here with a question that's been troubling me regarding the edit-field-during-review add-on.
When using the following code in the template, it allows modifications but fails to save：

<div id="A1">{{edit:Frontside}}</div>

<script>
function replaceCommaInValue() {
                       var element = document.getElementById('A1');
            if (element) {
                               var value = element.innerHTML;                                
var newValue = value.replace(/!/g, '-');                               
element.innerHTML = newValue;                 
            } 
        }
replaceCommaInValue()
</script>

**Comment by Seven430** [comment]
I’m a beginner, so if you’re available, could you please take a look? I would appreciate it.

**Comment by kelciour** [comment]
The add-on saves changes when the editable element loses focus by calling this JavaScript code.

```JavaScript
pycmd(`ankisave#${fld}#${nid}#${value}`);
```

`fld` is the name of the field
`nid` is the id of the note

Here's an example from https://github.com/kelciour/edit-field-during-review/issues/14

```python
...

<div id="elem" hidden>{{edit:Back}}</div>

<script>
function saveScrollPosition() {
  elem = document.querySelector('#elem [contenteditable]');
  fld = "Back";
  nid = elem.dataset.nid;
  value = window.scrollY;
  pycmd(`ankisave#${fld}#${nid}#${value}`);
}

document.onkeyup = function(event) {
  if (event.code == 'KeyD' && (event.ctrlKey || event.metaKey)) {
    saveScrollPosition();
  }
};
</script>
```

**Comment by Seven430** [comment]
Thank you for responding so quickly.

**Comment by Seven430** [comment]
Could you please let me know what the format of pycmd is when I use Edit Field During Review (Cloze)？

**Comment by kelciour** [comment]
It's ```pycmd(`EFDRC#${nid}#${fld}#${value}`);```

https://github.com/BlueGreenMagick/Edit-Field-During-Review-Cloze/blob/8fdc898e97f5114ddd79f5321db2f6bb7940c214/src/addon/reviewer.py#L147C28-L147C34

**Comment by Seven430** [comment]
Thanks a million
