### ISSUE TITLE
Anki 2.0 compatibility request

### ISSUE THREAD

**Issue by dsc321123** [kelciour/edit_field_during_review#2]
Thank you for this wonderful add-on. It is brilliant. Would you be willing to make it backward compatible with 2.0?

**Comment by kelciour** [comment]
Hi! I'm sorry for very late reply. If it's about Edit Field During Review add-on, I've just updated it to Anki 2.0.

As for now, the functionality should be the same, i.e. it's better not to use the add-on with fields that may contain cloze or audio tags.

To save any changes `Esc` button doesn't seem to work in Anki 2.0 to make the editable field lose focus, but clicking outside of the highlighted box seems to work fine.

Let me know if there're any problems.

**Comment by dsc321123** [comment]
Thank you! I will try it out.
    On Tuesday, July 2, 2019, 12:11:26 PM EDT, kelciour <notifications@github.com> wrote:  
 
 
Hi! I'm sorry for very late reply. If it's about Edit Field During Review add-on, I've just updated it to Anki 2.0.

As for now, the functionality should be the same, i.e. it's better not to use the add-on with fields that may contain cloze or audio tags.

To save any changes Esc button doesn't seem to work in Anki 2.0 to make the editable field lose focus, but clicking outside of the highlighted box seems to work fine.

Let me know if there're any problems.
