### ISSUE TITLE
Not saving changes

### ISSUE THREAD

**Issue by mjuzikfrik** [kelciour/edit_field_during_review#5]
Hello,

I can edit all the fields fine, but neither hitting escape button nor clicking somewhere else saves what I changed. It happens with my deck, but not with basic anki temple for some reason. I'm attaching the deck in question for reference.

https://drive.google.com/file/d/1v5vQC8QP7BbAGJyzvK25fz4HttNhuv8W/view?usp=sharing

**Comment by kelciour** [comment]
Thanks for the report! As for now, please add the following code at the end of the back template to make it work again.

    <script>
      $("[contenteditable=true][data-field]").blur(function() {
          pycmd("ankisave#" + $(this).data("field") + "#" + $(this).html());
      });
    </script>

I hope I'll have the updated version of the add-on by the end of the week and this fix won't be needed.

**Comment by mjuzikfrik** [comment]
It does work indeed. Thank you!
